### ISSUE TITLE
dataset template

### ISSUE THREAD

**Issue by TLedTS** [JaniceLC/PyTorch-VisNet#1]
Hello guys ,
    Thanks for your sharing. I want to apply it on my own dataset. However the dataset template is missing.
    So could you please share it again? 
    Thanks a lot!

**Comment by JaniceLC** [comment]
Hi, 
We provided a data loader template for VisNet named [frosi_dataset](https://github.com/JaniceLC/PyTorch-VisNet/blob/master/data/frosi_dataset.py). You can modify it according to your own datasets.
