### ISSUE TITLE
one question about VisNet

### ISSUE THREAD

**Issue by daipeizhe** [JaniceLC/PyTorch-VisNet#2]
Did you just implement the VisNet network structure, but this project cannot be used to realize VisNet's visibility prediction？

**Comment by JaniceLC** [comment]
Yes, we implemented the network structure based on the paper. However, the result is not promising as stated in the paper. I cannot find more detail in the paper.

**Comment by JaniceLC** [comment]
Closed

**Comment by daipeizhe** [comment]
thanks for your reply！

发自我的iPhone
