### ISSUE TITLE
Where is the .pth file？

### ISSUE THREAD

**Issue by Wing100** [JaniceLC/PyTorch-VisNet#3]
Hi, I did not find the .pth file. Where can I download this price?

**Comment by THE17** [comment]
Can you share the Dataset with us please ?

**Comment by muyeqingfeng** [comment]
That's what I want to ask.

**Comment by JaniceLC** [comment]
I implemented the model based on the original paper. However, I don't have the access to FROSI database as well. Thus, no model .pth are available on my side. But, you can train the model based on some other public visibility datasets.
