### ISSUE TITLE
A question about the pre-processing of data. 

### ISSUE THREAD

**Issue by muyeqingfeng** [JaniceLC/PyTorch-VisNet#6]
When I use the 3 streams code to processing data and display the result, I am unable to achieve the expected results。Stream 1 (FFT filter) is an all black image. I'm so confused

```python
    def data_process(self, image):
        im2freq = lambda data: fp.rfft(fp.rfft(data, axis=0), axis=1)
        image = np.asarray(image)  # numpy image

        stream1 = im2freq(image)
        open_cv_image = image[:, :, ::-1].copy()
        im_gray = cv2.cvtColor(open_cv_image, cv2.COLOR_BGR2GRAY)
        stream2 = cv2.applyColorMap(im_gray, cv2.COLORMAP_JET)
        stream2 = np.asarray(stream2)

        remmax = lambda x: x / x.max()
        remmin = lambda x: x - np.amin(x, axis=(0, 1), keepdims=True)
        touint8 = lambda x: (remmax(remmin(x)) * (256 - 1e-4)).astype('uint8')
        stream1 = touint8(stream1)

        image = Image.fromarray(image)
        stream2 = Image.fromarray(stream2)
        stream1 = Image.fromarray(stream1)

        image = self.transform(image)
        stream1 = self.transform(stream1)
        stream2 = self.transform(stream2)

        return stream1, stream2, image
```

![image](https://github.com/JaniceLC/PyTorch-VisNet/assets/30143418/35fb561f-acdc-4061-b1bc-09ba94a4023d)

**Comment by garyfanhku** [comment]
Could be visualization issue. Could you check the raw numpy array of stream1?

**Comment by muyeqingfeng** [comment]
![image](https://github.com/JaniceLC/PyTorch-VisNet/assets/30143418/f44039dd-d276-48ec-887c-ce8578bd6e93)
![image](https://github.com/JaniceLC/PyTorch-VisNet/assets/30143418/b59879e7-c678-436c-ac4c-7477090c274b)
![image](https://github.com/JaniceLC/PyTorch-VisNet/assets/30143418/db458dea-d15c-4a82-89b9-cd13b9b440b2)
![image](https://github.com/JaniceLC/PyTorch-VisNet/assets/30143418/2ca8b07e-92d3-4aa9-b5a9-da1cb30b1f15)

That's so strange...

**Comment by muyeqingfeng** [comment]
> ![image](https://user-images.githubusercontent.com/30143418/279641456-f44039dd-d276-48ec-887c-ce8578bd6e93.png) ![image](https://user-images.githubusercontent.com/30143418/279641493-b59879e7-c678-436c-ac4c-7477090c274b.png) ![image](https://user-images.githubusercontent.com/30143418/279643019-db458dea-d15c-4a82-89b9-cd13b9b440b2.png) ![image](https://user-images.githubusercontent.com/30143418/279643712-2ca8b07e-92d3-4aa9-b5a9-da1cb30b1f15.png)
> 
> That's so strange...

**Comment by muyeqingfeng** [comment]
> Could be visualization issue. Could you check the raw numpy array of stream1?

https://github.com/JaniceLC/PyTorch-VisNet/issues/6#issuecomment-1788713317

**Comment by JaniceLC** [comment]
Hi, @muyeqingfeng,

if you look into the numbers in stream1, the values are around 25, which are small values relative to 255. Thus, it is normal for the visualization to be black. As it is a kind of frequency, it may not be suitable to be visualized as a usual image. You can test the performance with/without stream 1 to see if it makes a difference or not. 

Meanwhile, you can check the technical details in the original papers. if you find any misalignment, pull requests are welcomed!

Thank you very much.
